basePath: /v1
definitions:
  models.ChangePassword:
    properties:
      email:
        type: string
      newPassword:
        type: string
      oldPassword:
        type: string
    type: object
  models.LoginUserPassword:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.ParamFilterProject:
    properties:
      page:
        type: integer
      size:
        type: integer
    type: object
  models.ParamSearchProject:
    properties:
      page:
        type: integer
      size:
        type: integer
    type: object
  models.RegistrationUserUsingPassword:
    properties:
      description:
        type: string
      email:
        type: string
      fullname:
        type: string
      location:
        type: integer
      password:
        type: string
      skills:
        type: string
      username:
        type: string
    type: object
  models.ResetPassword:
    properties:
      email:
        type: string
    type: object
  models.ResponseWithNoBody:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    name: API Support
  description: Swagger API for Golang Project PMS + Freelancer.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths:
  /allCountries:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Getting all list of countries
      tags:
      - Location
  /allSkills:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Getting all list of skills
      tags:
      - Skills
  /change-password:
    put:
      consumes:
      - application/json
      parameters:
      - description: Information needed to change password
        in: body
        name: Info
        required: true
        schema:
          $ref: '#/definitions/models.ChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Register new user using email and password
      tags:
      - User
  /filterProject:
    post:
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Filter project based on keyword
      tags:
      - Project
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account
        in: body
        name: parameter
        required: true
        schema:
          $ref: '#/definitions/models.LoginUserPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Login user using email and password
      tags:
      - User
  /logout:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Logout
      tags:
      - User
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.RegistrationUserUsingPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Register new user using email and password
      tags:
      - User
  /resetPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: Information needed to change password
        in: body
        name: Info
        required: true
        schema:
          $ref: '#/definitions/models.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Reset Password (Forget Password Feature)
      tags:
      - User
  /searchProject:
    get:
      parameters:
      - in: query
        name: page
        type: integer
      - in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ResponseWithNoBody'
      summary: Search Project initially
      tags:
      - Project
swagger: "2.0"
